-- Support for "Delete my account and all my data" (Profile Settings, web only).
--
-- Two pre-existing gaps would otherwise make admin.auth.admin.deleteUser()
-- fail outright with a foreign-key violation:
--
--  1. profiles.id references auth.users(id) with NO ON DELETE action
--     (NO ACTION/RESTRICT by default), so a profile row blocks deleting its
--     own auth user. A profile should never outlive its auth user, so this
--     should have been CASCADE from the start.
--  2. lobby_access_lists.added_by references auth.users(id) with no ON
--     DELETE action either -- if the user being deleted ever added someone
--     else to an access list on a lobby they don't own, that row would also
--     block deletion. SET NULL preserves the access-list entry itself and
--     just clears "who added them", which is fine -- we don't need to know
--     that forever.
--
-- Constraint names are looked up dynamically (rather than hardcoded) since
-- they were originally auto-generated by Postgres and this avoids any risk
-- of guessing wrong.
--
-- Everything else needed for account deletion already cascades correctly:
-- lobbies.owner_user_id, lobby_access_lists.user_id, lobby_sessions.user_id,
-- and pinterest_connections.user_id are all already ON DELETE CASCADE.
--
-- traces.user_id / layers.user_id are plain `text` columns with NO foreign
-- key at all (a historical `ADD COLUMN IF NOT EXISTS ... REFERENCES` no-op'd
-- because the columns already existed as text) -- no cascade would ever
-- touch content the deleted user created in OTHER users' shared atriums.
-- Per product decision that content should survive (so a shared atrium
-- doesn't lose pieces other people are relying on), just no longer
-- attributed to the deleted account -- the delete-account Edge Function
-- anonymizes those rows' user_id/username instead of deleting them. Content
-- in atriums the user owns doesn't need separate handling: it's wiped
-- (anonymized rows included) by the lobbies -> traces/layers cascade below.

DO $$
DECLARE
  con_name text;
BEGIN
  SELECT conname INTO con_name
  FROM pg_constraint
  WHERE conrelid = 'public.profiles'::regclass
    AND contype = 'f'
    AND conkey = ARRAY[(
      SELECT attnum FROM pg_attribute
      WHERE attrelid = 'public.profiles'::regclass AND attname = 'id'
    )];

  IF con_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.profiles DROP CONSTRAINT %I', con_name);
  END IF;

  ALTER TABLE public.profiles
    ADD CONSTRAINT profiles_id_fkey
    FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
END $$;

DO $$
DECLARE
  con_name text;
BEGIN
  SELECT conname INTO con_name
  FROM pg_constraint
  WHERE conrelid = 'public.lobby_access_lists'::regclass
    AND contype = 'f'
    AND conkey = ARRAY[(
      SELECT attnum FROM pg_attribute
      WHERE attrelid = 'public.lobby_access_lists'::regclass AND attname = 'added_by'
    )];

  IF con_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.lobby_access_lists DROP CONSTRAINT %I', con_name);
  END IF;

  ALTER TABLE public.lobby_access_lists
    ADD CONSTRAINT lobby_access_lists_added_by_fkey
    FOREIGN KEY (added_by) REFERENCES auth.users(id) ON DELETE SET NULL;
END $$;

-- admin_user_ids is a plain uuid[] column on lobbies with no FK possible, so
-- there's nothing for a cascade to clean up when a user is deleted -- strip
-- them from any OTHER lobby's admin list explicitly (lobbies they own are
-- deleted wholesale by the owner_user_id cascade regardless).
--
-- Deliberately locked down to service_role only: this takes an arbitrary
-- p_user_id (not implicitly scoped to auth.uid()), so if left callable by
-- ordinary authenticated clients, anyone could strip any other user's admin
-- status from a lobby they don't control.
CREATE OR REPLACE FUNCTION public.remove_user_from_all_admin_lists(p_user_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.lobbies
  SET admin_user_ids = array_remove(admin_user_ids, p_user_id)
  WHERE p_user_id = ANY(admin_user_ids);
END;
$$;

REVOKE ALL ON FUNCTION public.remove_user_from_all_admin_lists(uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.remove_user_from_all_admin_lists(uuid) TO service_role;

COMMENT ON FUNCTION public.remove_user_from_all_admin_lists IS 'Service-role only. Strips a user id out of every lobby admin_user_ids array they appear in (except lobbies they own, which get deleted wholesale). Used by the delete-account Edge Function.';
